/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as FuelVerificationRouteImport } from './routes/fuel-verification'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelVerificationRoute = FuelVerificationRouteImport.update({
  id: '/fuel-verification',
  path: '/fuel-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/fuel-verification': typeof FuelVerificationRoute
  '/maintenance': typeof MaintenanceRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/fuel-verification': typeof FuelVerificationRoute
  '/maintenance': typeof MaintenanceRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/driver-portal': typeof DriverPortalRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/fuel': typeof FuelRoute
  '/fuel-verification': typeof FuelVerificationRoute
  '/maintenance': typeof MaintenanceRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fuel'
    | '/fuel-verification'
    | '/maintenance'
    | '/trips'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fuel'
    | '/fuel-verification'
    | '/maintenance'
    | '/trips'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/driver-portal'
    | '/drivers'
    | '/expenses'
    | '/fuel'
    | '/fuel-verification'
    | '/maintenance'
    | '/trips'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DriverPortalRoute: typeof DriverPortalRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  FuelRoute: typeof FuelRoute
  FuelVerificationRoute: typeof FuelVerificationRoute
  MaintenanceRoute: typeof MaintenanceRoute
  TripsRoute: typeof TripsRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel-verification': {
      id: '/fuel-verification'
      path: '/fuel-verification'
      fullPath: '/fuel-verification'
      preLoaderRoute: typeof FuelVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DriverPortalRoute: DriverPortalRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  FuelRoute: FuelRoute,
  FuelVerificationRoute: FuelVerificationRoute,
  MaintenanceRoute: MaintenanceRoute,
  TripsRoute: TripsRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
